_wandb:
    value:
        cli_version: 0.25.0
        e:
            nyeu7aei704q7ab9n84yvykei4gcqjvd:
                apple:
                    ecpuCores: 6
                    gpuCores: 10
                    memoryGb: 24
                    name: Apple M4
                    pcpuCores: 4
                    ramTotalBytes: "25769803776"
                args:
                    - --config
                    - spoke/config.yaml
                codePath: .venv/bin/mlx_lm.lora
                codePathLocal: .venv/bin/mlx_lm.lora
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "494384795648"
                        used: "467963195392"
                email: rajkumar.sandheep@gmail.com
                executable: /Users/lolrazh/Documents/Projects/mlx/.venv/bin/python3.11
                git:
                    commit: db53929b2eb3dda4e54a6358e23db0d407294c32
                    remote: https://github.com/lolrazh/mlx.git
                host: Sandys-MacBook-Air.local
                memory:
                    total: "25769803776"
                os: macOS-26.2-arm64-arm-64bit
                program: /Users/lolrazh/Documents/Projects/mlx/.venv/bin/mlx_lm.lora
                python: CPython 3.11.0
                root: ./spoke/adapters-llama3-t2
                startedAt: "2026-03-03T09:53:48.190715Z"
                writerId: nyeu7aei704q7ab9n84yvykei4gcqjvd
        m: []
        python_version: 3.11.0
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
            "3":
                - 13
                - 16
                - 61
            "4": 3.11.0
            "5": 0.25.0
            "6": 5.0.0rc3
            "12": 0.25.0
            "13": darwin-arm64
adapter_path:
    value: ./spoke/adapters-llama3-t2
batch_size:
    value: 4
config:
    value: spoke/config.yaml
data:
    value: ./spoke/data/v4
fine_tune_type:
    value: lora
grad_accumulation_steps:
    value: 1
grad_checkpoint:
    value: false
iters:
    value: 2000
learning_rate:
    value: 1e-05
lora_parameters:
    value:
        dropout: 0.05
        rank: 8
        scale: 2
lr_schedule:
    value: null
mask_prompt:
    value: true
max_seq_length:
    value: 512
model:
    value: mlx-community/Llama-3.2-3B-Instruct-bf16
num_layers:
    value: 28
optimizer:
    value: adam
project_name:
    value: null
report_to:
    value: wandb
resume_adapter_file:
    value: null
save_every:
    value: 100
seed:
    value: 42
steps_per_eval:
    value: 50
steps_per_report:
    value: 10
test:
    value: false
test_batches:
    value: 500
train:
    value: true
val_batches:
    value: 25
